
(function(){
'use strict';
const STATE_NAMES={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',DC:'District of Columbia',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming'};
const STATE_ABBR=Object.fromEntries(Object.entries(STATE_NAMES).map(([abbr,name])=>[normalize(name),abbr]));
let locationRows=[];
let byFips=new Map();
function normalize(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function escapeText(value){return document.createTextNode(String(value||''))}
function track(name,params){if(typeof window.gtag==='function')window.gtag('event',name,params||{})}
async function fetchJson(url,timeoutMs){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),timeoutMs||8000);try{const res=await fetch(url,{headers:{Accept:'application/json'},signal:ctrl.signal});if(!res.ok)throw new Error('HTTP '+res.status);return await res.json()}finally{clearTimeout(timer)}}
async function loadRows(){if(locationRows.length)return locationRows;const data=await fetchJson('/data/location-index.json',10000);locationRows=Array.isArray(data.records)?data.records:[];byFips=new Map(locationRows.map(row=>[row.f,row]));return locationRows}
function localMatches(query){const n=normalize(query);if(n.length<2)return[];const tokens=n.split(' ').filter(Boolean);return locationRows.map(row=>{const hay=normalize(row.n+' '+row.s+' '+row.a);if(!tokens.every(token=>hay.includes(token)))return null;let score=0;const county=normalize(row.n),state=normalize(row.s);if(n===county||n===county+' '+state||n===county+' '+normalize(row.a))score+=100;if(county.startsWith(n))score+=35;if(hay.startsWith(n))score+=20;if(row.v)score+=6;score+=Math.min(Number(row.p||0),5);return{row,score}}).filter(Boolean).sort((a,b)=>b.score-a.score||a.row.n.localeCompare(b.row.n)).map(item=>item.row).slice(0,12)}
function parsedCityState(query){let parts=String(query||'').trim().split(',').map(x=>x.trim()).filter(Boolean);let city='',state='';if(parts.length>=2){city=parts.slice(0,-1).join(' ');state=parts[parts.length-1]}else{const words=String(query||'').trim().split(/\s+/);if(words.length>=2){const last=normalize(words[words.length-1]);if(STATE_NAMES[words[words.length-1].toUpperCase()]||STATE_ABBR[last]){state=words.pop();city=words.join(' ')}}}if(!city||!state)return null;const upper=state.toUpperCase();const abbr=STATE_NAMES[upper]?upper:STATE_ABBR[normalize(state)];return abbr?{city,state:abbr}:null}
async function fipsFromCoordinates(lat,lon){const key='ss-fips:'+Number(lat).toFixed(4)+','+Number(lon).toFixed(4);try{const cached=sessionStorage.getItem(key);if(cached)return cached}catch(_e){}const fcc='https://geo.fcc.gov/api/census/block/find?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lon)+'&format=json';try{const data=await fetchJson(fcc,7000);const fips=data&&data.County&&String(data.County.FIPS||'').padStart(5,'0');if(fips&&byFips.has(fips)){try{sessionStorage.setItem(key,fips)}catch(_e){}return fips}}catch(_e){}const census='https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x='+encodeURIComponent(lon)+'&y='+encodeURIComponent(lat)+'&benchmark=Public_AR_Current&vintage=Current_Current&format=json';const data=await fetchJson(census,8000);const counties=data&&data.result&&data.result.geographies&&data.result.geographies.Counties;const county=Array.isArray(counties)?counties[0]:null;const fips=county?String(county.STATE||'').padStart(2,'0')+String(county.COUNTY||'').padStart(3,'0'):'';if(fips&&byFips.has(fips)){try{sessionStorage.setItem(key,fips)}catch(_e){}return fips}throw new Error('County could not be resolved')}
async function remoteMatches(query){const zip=String(query||'').trim().match(/^\d{5}$/);let places=[];let label='';if(zip){const data=await fetchJson('https://api.zippopotam.us/us/'+zip[0],8000);places=Array.isArray(data.places)?data.places:[];label='ZIP '+zip[0]}else{const parsed=parsedCityState(query);if(!parsed)return{rows:[],label:'',reason:'Enter a five-digit ZIP code, a city and state, or a county and state.'};const data=await fetchJson('https://api.zippopotam.us/us/'+parsed.state.toLowerCase()+'/'+encodeURIComponent(parsed.city),8000);places=Array.isArray(data.places)?data.places:[];label=parsed.city+', '+parsed.state}const unique=[];const seen=new Set();for(const place of places){const lat=place.latitude,lon=place.longitude;if(lat==null||lon==null)continue;const coord=Number(lat).toFixed(4)+','+Number(lon).toFixed(4);if(seen.has(coord))continue;seen.add(coord);unique.push(place);if(unique.length>=12)break}const results=await Promise.allSettled(unique.map(place=>fipsFromCoordinates(place.latitude,place.longitude)));const fips=[...new Set(results.filter(x=>x.status==='fulfilled').map(x=>x.value))];return{rows:fips.map(code=>byFips.get(code)).filter(Boolean),label,reason:''}}
function clearNode(node){while(node.firstChild)node.removeChild(node.firstChild)}
function makeResult(row){const article=document.createElement('article');article.className='search-result';const left=document.createElement('div');const title=document.createElement('div');title.className='result-title';title.appendChild(escapeText(row.n+', '+row.s));const meta=document.createElement('div');meta.className='result-meta';const status=row.v?'Source-checked county guide':'Official help page · local guide in progress';const services=Number(row.p||0)>0?' · '+row.p+' local service listing'+(Number(row.p)===1?'':'s'):'';meta.appendChild(escapeText(status+services));left.append(title,meta);const link=document.createElement('a');link.className='result-link';link.href=row.u;link.appendChild(escapeText(row.v?'Open county guide':'Open county page'));article.append(left,link);return article}
function renderResults(root,rows,statusText){const out=root.querySelector('[data-location-results]'),status=root.querySelector('[data-location-status]');clearNode(out);rows.forEach(row=>out.appendChild(makeResult(row)));status.hidden=false;status.textContent=statusText}
async function runSearch(root,query){const button=root.querySelector('button[type="submit"]'),status=root.querySelector('[data-location-status]');button.disabled=true;button.textContent='Searching…';status.hidden=false;status.textContent='Checking the national county index…';try{await loadRows();const local=localMatches(query);const normalizedQuery=normalize(query);const first=local[0];const exactLocal=Boolean(first&&[normalize(first.n),normalize(first.n+' '+first.s),normalize(first.n+' '+first.a)].includes(normalizedQuery));const zip=/^\d{5}$/.test(String(query).trim());const city=parsedCityState(query);if(local.length&&!zip&&(!city||exactLocal)){renderResults(root,local,'Showing '+local.length+' county match'+(local.length===1?'':'es')+'.');track('location_search',{search_type:'county_or_state',result_count:local.length,query_length:String(query).length});return}if(zip||city){status.textContent='Resolving the location to a county…';try{const remote=await remoteMatches(query);if(remote.rows.length){renderResults(root,remote.rows,'Likely '+(remote.rows.length===1?'county':'counties')+' for '+remote.label+'. Confirm the property county before using permit information.');track('location_search',{search_type:zip?'zip':'city_state',result_count:remote.rows.length,query_length:String(query).length});return}renderResults(root,local,remote.reason||'No county could be resolved. Try the county name and state.')}catch(_e){renderResults(root,local,local.length?'The live city/ZIP resolver was unavailable. Showing close county-name matches.':'The live city/ZIP resolver is temporarily unavailable. Search the county and state or browse by state below.');track('location_search_error',{search_type:zip?'zip':'city_state'})}return}renderResults(root,local,local.length?'Showing '+local.length+' county match'+(local.length===1?'':'es')+'.':'No matching county found. Try “County, State,” a five-digit ZIP, or “City, ST.”');track('location_search',{search_type:'county_or_state',result_count:local.length,query_length:String(query).length})}finally{button.disabled=false;button.textContent='Find my county'}}
function initSearch(root){const form=root.querySelector('form'),input=root.querySelector('input[type="search"]');if(!form||!input)return;form.addEventListener('submit',event=>{event.preventDefault();const query=input.value.trim();if(!query){input.focus();return}runSearch(root,query)});const params=new URLSearchParams(location.search);const q=params.get('q');if(q){input.value=q;runSearch(root,q)}}
function initMenu(){const button=document.querySelector('[data-menu-button]'),menu=document.querySelector('[data-mobile-nav]');if(!button||!menu)return;button.addEventListener('click',()=>{const open=menu.getAttribute('data-open')==='true';menu.setAttribute('data-open',open?'false':'true');button.setAttribute('aria-expanded',open?'false':'true')})}
document.addEventListener('DOMContentLoaded',()=>{initMenu();document.querySelectorAll('[data-location-search]').forEach(initSearch);loadRows().catch(()=>{})});
})();
